# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Mrs. Volz at MK
email: jvolz@mhrd.org
description: > # this means to ignore newlines until "baseurl:"
  Site hosted by Jennifer Volz, mathematics teacher and AP Comp Sci Principles 
  teacher at Morris Knolls High School, Rockaway, NJ
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jvolzmk.github.io" # the base hostname & protocol for your site
twitter_username: jenparzekvolz 
github_username:  jvolzmk

# Build settings
markdown: kramdown
